import { exec, type ExecResult } from "../util/exec.js";
import { writeFileAtomic } from "../util/fsx.js";

/**
 * Deterministic baseline: the baseline phase is mechanical — run the build,
 * record warnings/errors — so when build.command is configured there is no
 * reason to spend an agent session on it. This module produces the same
 * existing-warnings.md contract the agent template specifies (including the
 * trailing BUGZINGA_VERDICT line), so every downstream consumer is unaffected.
 */

export type BaselineVerdict = "complete" | "build-broken";

export interface DeterministicBaselineOptions {
  bugId: string;
  buildCommand: string;
  testCommand: string | null;
  /** The bug's git worktree — commands run here. */
  cwd: string;
  artifactPath: string;
  timeoutMs: number;
}

/** Run a configured shell command string cross-platform. */
function shell(command: string, cwd: string, timeoutMs: number): Promise<ExecResult> {
  return process.platform === "win32"
    ? exec(process.env.ComSpec ?? "cmd.exe", ["/d", "/s", "/c", command], { cwd, timeoutMs })
    : exec("sh", ["-c", command], { cwd, timeoutMs });
}

const MAX_SECTION_LINES = 100;
const TAIL_LINES = 80;

export const WARNING_PATTERN = /\b(warning|warn)\b/i;
export const ERROR_PATTERN = /\b(error|failed)\b/i;

/** Unique trimmed lines of `output` matching `pattern`, in first-seen order. */
export function matchLines(output: string, pattern: RegExp): string[] {
  const seen = new Set<string>();
  for (const line of output.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed && pattern.test(trimmed)) seen.add(trimmed);
  }
  return [...seen];
}

function section(lines: string[]): string {
  if (lines.length === 0) return "None";
  const shown = lines.slice(0, MAX_SECTION_LINES);
  const omitted = lines.length - shown.length;
  return shown.join("\n") + (omitted > 0 ? `\n… (${omitted} more)` : "");
}

function tail(output: string): string {
  const lines = output.split(/\r?\n/);
  return lines.slice(Math.max(0, lines.length - TAIL_LINES)).join("\n").trim() || "(no output)";
}

/**
 * Run build (and tests, informationally) and write the baseline artifact.
 *
 * Verdict policy: the build command exiting non-zero (or timing out) on an
 * untouched checkout means no fix can ever be verified against it →
 * build-broken. Test failures never affect the verdict — a RED repro test
 * from the reproduce phase is expected here. Projects whose build is
 * known-red can set pipeline.deterministicBaseline=false to let an agent
 * judge the baseline instead.
 */
export async function runDeterministicBaseline(
  opts: DeterministicBaselineOptions,
): Promise<BaselineVerdict> {
  const capturedAt = new Date().toISOString();
  const build = await shell(opts.buildCommand, opts.cwd, opts.timeoutMs);
  const buildOutput = `${build.stdout}\n${build.stderr}`.trim();
  const buildOk = build.code === 0 && !build.timedOut;
  const verdict: BaselineVerdict = buildOk ? "complete" : "build-broken";

  const parts: string[] = [
    `# Baseline Build Report: ${opts.bugId}`,
    `Captured: ${capturedAt} (deterministic — generated by Bugzinga without an agent)`,
    "",
    "## Build Command",
    `\`${opts.buildCommand}\``,
    "",
    "## Exit Code",
    `${build.code ?? "killed"}${build.timedOut ? " (timed out)" : ""}`,
    "",
    "## Errors",
    section(matchLines(buildOutput, ERROR_PATTERN)),
    "",
    "## Warnings",
    section(matchLines(buildOutput, WARNING_PATTERN)),
  ];

  if (buildOk && opts.testCommand) {
    const tests = await shell(opts.testCommand, opts.cwd, opts.timeoutMs);
    const testOutput = `${tests.stdout}\n${tests.stderr}`.trim();
    parts.push(
      "",
      "## Test Baseline (informational — failures here are expected, e.g. a RED repro test)",
      `\`${opts.testCommand}\` → exit ${tests.code ?? "killed"}${tests.timedOut ? " (timed out)" : ""}`,
      "",
      "### Failing test lines",
      section(matchLines(testOutput, /\b(fail|failed|failing|✗|×)\b/i)),
    );
  }

  parts.push(
    "",
    "## Output Tail",
    "```",
    tail(buildOutput),
    "```",
    "",
    ...(buildOk
      ? []
      : [
          "The build fails on an untouched checkout, so no fix can be verified against it. " +
            "Fix the build first, or set `pipeline.deterministicBaseline: false` to have an agent judge a known-red baseline.",
          "",
        ]),
    `BUGZINGA_VERDICT: ${verdict}`,
    "",
  );

  writeFileAtomic(opts.artifactPath, parts.join("\n"));
  return verdict;
}
